export const data = [
    {
        id: 1,
        title: 'Introduction to React Hooks',
        subtitle: 'Learn the basics of React Hooks and how to use them in your projects.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'John Doe',
        image: 'https://source.unsplash.com/800x400/?react,programming',
    },
    {
        id: 2,
        title: 'CSS-in-JS: Styling React Components',
        subtitle: 'Explore different CSS-in-JS libraries and techniques for styling React components.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Jane Smith',
        image: 'https://source.unsplash.com/800x400/?css,design',
    },
    {
        id: 3,
        title: 'JavaScript ES6: Arrow Functions and Destructuring',
        subtitle: 'Deep dive into Arrow Functions and Destructuring in JavaScript ES6.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Alex Johnson',
        image: 'https://source.unsplash.com/800x400/?javascript,code',
    },
    {
        id: 4,
        title: 'Responsive Web Design with Flexbox',
        subtitle: 'Master the art of building responsive layouts using CSS Flexbox.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Emily Brown',
        image: 'https://source.unsplash.com/800x400/?flexbox,design',
    },
    {
        id: 5,
        title: 'Node.js Basics: Getting Started with Server-Side JavaScript',
        subtitle: 'Explore the fundamentals of Node.js and its role in server-side development.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Chris Wilson',
        image: 'https://source.unsplash.com/800x400/?nodejs,code',
    },
    {
        id: 6,
        title: 'GraphQL: A Query Language for APIs',
        subtitle: 'Introduction to GraphQL and how it revolutionizes API development.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Sophia Carter',
        image: 'https://source.unsplash.com/800x400/?graphql,programming',
    },
    {
        id: 7,
        title: 'State Management in React: Redux and Context API',
        subtitle: 'Comparing state management options in React, including Redux and Context API.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'David Miller',
        image: 'https://source.unsplash.com/800x400/?react,redux',
    },
    {
        id: 8,
        title: 'Web Accessibility: A Comprehensive Guide',
        subtitle: 'Ensuring your web applications are accessible to all users.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Grace White',
        image: 'https://source.unsplash.com/800x400/?accessibility,design',
    },
    {
        id: 9,
        title: 'Testing JavaScript Applications with Jest',
        subtitle: 'Introduction to Jest for testing JavaScript applications.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Michael Green',
        image: 'https://source.unsplash.com/800x400/?jest,programming',
    },
    {
        id: 10,
        title: 'Deploying React Apps: From Development to Production',
        subtitle: 'Guide to deploying React applications on various platforms.',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
        author: 'Jessica Adams',
        image: 'https://source.unsplash.com/800x400/?react,deployment',
    },
];